# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: remove docker images and stop server
        uses: fifsky/ssh-action@master
        with:
          command: |
            docker-compose up -d
            docker-compose down
            docker rmi root_node
          host: ${{ secrets.SERVER_HOST }}
          user: root
          key: ${{ secrets.SERVER_KEY }}
      - name: deploy to server
        uses: easingthemes/ssh-deploy@v2.1.1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_KEY }}
          REMOTE_HOST: ${{ secrets.SERVER_HOST }}
          REMOTE_USER: "root"
          ARGS: "-avzr --delete"
          SOURCE: "/"
          TARGET: "/root/app/backend-resource"
      - name: start server
        uses: fifsky/ssh-action@master
        with:
          command: |
            docker-compose up -d
          host: ${{ secrets.SERVER_HOST }}
          user: root
          key: ${{ secrets.SERVER_KEY }}
