# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: remove docker images and stop server
        uses: fifsky/ssh-action@master
        with:
          command: |
            docker-compose down
            docker rmi root_node
          host: "111.229.221.29"
          user: root
          key: ${{ secrets.SERVER_KEY }}
    - name: deploy to server
      uses: easingthemes/ssh-deploy@v2.1.1
      env:
        # 本地.ssh文件下的私钥id_rsa，存在secrets的TOKEN中
        SSH_PRIVATE_KEY: ${{ secrets.SERVER_KEY }}
        # 服务器域名
        REMOTE_HOST: "111.229.221.29"
        # 腾讯云默认用户名为root
        REMOTE_USER: "root"
        # 复制操作的参数。"-avzr --delete"意味部署时清空服务器目标目录下的文件
        ARGS: "-avzr --delete"
        # 源目录，相对于$GITHUB_WORKSPACE根目录的路径
        SOURCE: "/"
        # 目标目录
        TARGET: "/root/app/backend-resource"
    - name: start server
      uses: fifsky/ssh-action@master
      with:
        command: |
          docker-compose up -d
        host: "111.229.221.29"
        user: root
        key: ${{ secrets.SERVER_KEY }}
